name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          outputs: type=tar,dest=/tmp/image.tar
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gantoo:latest

      - name: 'Tar /var/cache/binpkgs'
        run: tar tvf /tmp/image.tar var/cache/binpkgs
      - name: 'Upload binpkgs.tar'
        uses: actions/upload-artifact@v2
        with:
          name: binary-cache
          path: var/
