name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gantoo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
