name: Docker Build
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/386

    steps:

      - uses: actions/checkout@v2

      - run: mkdir -p /tmp/cache
      - name: Cache /binpkgs
        uses: pat-s/always-upload-cache@main
        env:
          cache-name: cache-binpkgs-musl-20211108-split
        with:
          path: /tmp/cache
          key: "${{ env.cache-name }}-${{ matrix.platform }}-${{ github.sha }}"
          restore-keys: "${{ env.cache-name }}-${{ matrix.platform }}"

      - name: Fake .tar, if necessary
        run: |
          cd /tmp/cache
          mkdir -p binpkgs
          test -f binpkgs.tar && tar tf binpkgs.tar
          test -f binpkgs.tar || tar cf binpkgs.tar binpkgs
          md5sum binpkgs.tar
          cp -v binpkgs.tar "$GITHUB_WORKSPACE"/

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          platforms: ${{ matrix.platform }}
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gantoo:musl
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Build Cache
        continue-on-error: true # NOTE: if layer cache hits, no /fs/ would exist
        if: always()
        run: |
          CONTAINER=$(docker ps -qa)
          docker exec $CONTAINER /bin/sh -c 'echo /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/' \
            | xargs -n1 echo \
            | while read -r file; do docker cp "$CONTAINER":"${file}" .; done
          docker exec $CONTAINER /bin/sh -c 'rm -rf /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/'
          rm -vf binpkgs.tar
          tar cf binpkgs.tar binpkgs/
          md5sum binpkgs.tar
          tar tf binpkgs.tar
          mv -v binpkgs.tar /tmp/cache

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15
