name: Linux Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:nomultilib
    steps:

      - name: 'Download binpkgs'
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: my-artifact
          workflow: main.yml
          workflow_conclusion: success
      - name: 'Unpack binpkgs'
        run: test -f binpkgs.tar && tar xvf binpkgs.tar -C / || true

      - name: 'Sync Portage'
        run: |
          mkdir -vp /var/db/repos/gentoo
          emerge-webrsync
      - name: 'Configure USE'
        run: |
          emerge -qbk app-portage/flaggie
          flaggie --strict --destructive-cleanup dev-vcs/git -perl
          flaggie --strict --destructive-cleanup +static-libs
          flaggie --strict --destructive-cleanup dev-lisp/sbcl +~amd64
          flaggie --strict --destructive-cleanup dev-lisp/asdf +~amd64
          flaggie --strict --destructive-cleanup dev-lisp/uiop +~amd64
          flaggie --strict --destructive-cleanup media-gfx/imagemagick:0/6.9.11-60 -openmp -cxx -bzip2 -zlib
          flaggie --strict --destructive-cleanup media-libs/sdl2-image +png
      - name: 'Add Overlay'
        run: |
          emerge -qbk app-admin/eselect app-eselect/eselect-repository dev-vcs/git
          mkdir -vp /etc/portage/repos.conf
          eselect repository add azimut git https://github.com/azimut/overlay.git
          emaint sync -r azimut

      - name: 'Install Packages'
        run: emerge -qbk media-libs/libsdl2 media-gfx/imagemagick:0/6.9.11-60 media-libs/sdl2-image =dev-lisp/sbcl-2.1.10::azimut

      - name: 'Tar /var/cache/binpkgs'
        run: tar cvf binpkgs.tar /var/cache/binpkgs
      - name: 'Upload binpkgs.tar'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: binpkgs.tar

      - name: 'DEBUG tools'
        if: ${{ failure() }}
        run: |
          emerge -qbk app-portage/gentoolkit app-portage/eix
          eix-update
      - name: 'DEBUG shell'
        if: ${{ failure() }}
        uses: seemethere/action-tmate@skip_dependency_installation
        with:
          install_dependencies: false
          sudo: false

