name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: binary-cache-musl-20211108
          workflow: main.yml
          workflow_conclusion: success
      - name: Fake .tar, if necessary
        run: |
          mkdir -p binpkgs
          test -f binpkgs.tar || tar -cf binpkgs.tar binpkgs
          md5sum binpkgs.tar

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: true
          tags: ghcr.io/azimut/gantoo/musl:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Build Cache
        run: |
          CONTAINER=$(docker ps -qa)
          docker exec $CONTAINER /bin/sh -c 'echo /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/' \
            | xargs -n1 echo \
            | while read -r file; do docker cp "$CONTAINER":"${file}" .; done
          docker exec $CONTAINER /bin/sh -c 'rm -rf /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/'
          rm -vf binpkgs.tar
          tar cf binpkgs.tar binpkgs/
          md5sum binpkgs.tar

      - uses: actions/upload-artifact@v2
        with:
          name: binary-cache-musl-20211108
          path: |
            binpkgs.tar

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
