name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: mkdir -p /tmp/cache
      - name: Cache /binpkgs
        uses: gerbal/always-cache@v1.0.3
        env:
          cache-name: cache-binpkgs-musl-20211108
        with:
          path: /tmp/cache
          key: "${{ env.cache-name }}-${{ github.sha }}"
          restore-keys: "${{ env.cache-name }}"

      - name: Fake .tar, if necessary
        run: |
          cd /tmp/cache
          mkdir -p binpkgs
          test -f binpkgs.tar && tar tf binpkgs.tar
          test -f binpkgs.tar || tar cf binpkgs.tar binpkgs
          md5sum binpkgs.tar
          mv -v binpkgs.tar "$GITHUB_WORKSPACE"/

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: true
          tags: ghcr.io/azimut/gantoo/musl:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Build Cache
        run: |
          CONTAINER=$(docker ps -qa)
          docker exec $CONTAINER /bin/sh -c 'echo /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/' \
            | xargs -n1 echo \
            | while read -r file; do docker cp "$CONTAINER":"${file}" .; done
          docker exec $CONTAINER /bin/sh -c 'rm -rf /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/*/fs/var/cache/binpkgs/'
          rm -vf binpkgs.tar /tmp/cache/binpkgs.tar
          tar cf binpkgs.tar binpkgs/
          md5sum binpkgs.tar
          tar tf binpkgs.tar
          mv -v binpkgs.tar /tmp/cache

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
