name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: binary-cache
          workflow: main.yml
          workflow_conclusion: success
      - name: Fake .tar, if necessary
        run: |
          mkdir -p distfiles binpkgs
          test -f distfiles.tar || tar -cf distfiles.tar distfiles
          test -f binpkgs.tar   || tar -cf binpkgs.tar   binpkgs
          rm -rf distfiles binpkgs
          md5sum distfiles.tar binpkgs.tar

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gantoo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Build Cache
        run: |
          docker cp $(docker ps -qa):/var/cache/distfiles .
          docker cp $(docker ps -qa):/var/cache/binpkgs   .
          tar cf distfiles.tar distfiles/
          tar cf binpkgs.tar   binpkgs/
          md5sum binpkgs.tar distfiles.tar
      - uses: actions/upload-artifact@v2
        with:
          name: binary-cache
          path: |
            distfiles.tar
            binpkgs.tar
