name: Docker Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download binpkgs'
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: binary-cache
          workflow: main.yml
          workflow_conclusion: success
      - name: 'Unpack binpkgs'
        run: |
          test -f binpkgs.tar && tar xvf binpkgs.tar -C / || true
          mkdir -vp /bin/pkgs

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azimut/gantoo:latest

      - name: 'Tar /var/cache/binpkgs'
        run: tar cvf binpkgs.tar /tmp/binpkgs
      - name: 'Upload binpkgs.tar'
        uses: actions/upload-artifact@v2
        with:
          name: binary-cache
          path: binpkgs.tar
